# Reference: Python Data Science Handbook

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

%autosave 9999
%matplotlib inline

Autosaving every 9999 seconds


DictVectorizer, LabelEncoder and OneHotEncoder

In [23]:
data = [
    {'price': 850000, 'rooms': 4, 'neighborhood': 'Queen Anne'},
    {'price': 700000, 'rooms': 3, 'neighborhood': 'Fremont'},
    {'price': 650000, 'rooms': 3, 'neighborhood': 'Wallingford'},
    {'price': 600000, 'rooms': 2, 'neighborhood': 'Fremont'}
]

In [51]:
from sklearn.feature_extraction import DictVectorizer
vec = DictVectorizer(sparse=False, dtype=np.int)
vec_data = vec.fit_transform(data)
vec_data

array([[     0,      1,      0, 850000,      4],
       [     1,      0,      0, 700000,      3],
       [     0,      0,      1, 650000,      3],
       [     1,      0,      0, 600000,      2]], dtype=int64)

In [27]:
vec.get_feature_names()

['neighborhood=Fremont',
 'neighborhood=Queen Anne',
 'neighborhood=Wallingford',
 'price',
 'rooms']

In [52]:
pd.DataFrame(vec_data,columns = vec.get_feature_names())

neighborhood=Fremont  neighborhood=Queen Anne  neighborhood=Wallingford  \
0                     0                        1                         0   
1                     1                        0                         0   
2                     0                        0                         1   
3                     1                        0                         0   

    price  rooms  
0  850000      4  
1  700000      3  
2  650000      3  
3  600000      2

In [29]:
data_df = pd.DataFrame(data)
data_df

neighborhood   price  rooms
0   Queen Anne  850000      4
1      Fremont  700000      3
2  Wallingford  650000      3
3      Fremont  600000      2

In [33]:
df1 = data_df.select_dtypes(include=[object])
df1

neighborhood
0   Queen Anne
1      Fremont
2  Wallingford
3      Fremont

In [36]:
from sklearn import preprocessing
encoder1 = preprocessing.LabelEncoder()
df2 = df1.apply(encoder1.fit_transform)
df2

neighborhood
0             1
1             0
2             2
3             0

In [48]:
encoder2 = preprocessing.OneHotEncoder(sparse=False)
encoder2.fit(df2)
onehotlabels = encoder2.transform(df2)
onehotlabels

array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

Text Features

In [41]:
sample = ['problem of evil',
          'evil queen',
          'horizon problem']

In [45]:
from sklearn.feature_extraction.text import CountVectorizer

vec = CountVectorizer()
X = vec.fit_transform(sample)
X

<3x5 sparse matrix of type '<class 'numpy.int64'>'
	with 7 stored elements in Compressed Sparse Row format>

In [46]:
pd.DataFrame(X.toarray(), columns=vec.get_feature_names())

evil  horizon  of  problem  queen
0     1        0   1        1      0
1     1        0   0        0      1
2     0        1   0        1      0

In [53]:
from sklearn.feature_extraction.text import TfidfVectorizer
vec = TfidfVectorizer()
X = vec.fit_transform(sample)
pd.DataFrame(X.toarray(), columns=vec.get_feature_names())

evil   horizon        of   problem     queen
0  0.517856  0.000000  0.680919  0.517856  0.000000
1  0.605349  0.000000  0.000000  0.000000  0.795961
2  0.000000  0.795961  0.000000  0.605349  0.000000

Image Features: CNN is preferred

Imputation of Missing Data: For a baseline imputation approach, using the mean, median, or most frequent value, Scikit-Learn provides the Imputer class:

In [54]:
from numpy import nan
X = np.array([[ nan, 0,   3  ],
              [ 3,   7,   9  ],
              [ 3,   5,   2  ],
              [ 4,   nan, 6  ],
              [ 8,   8,   1  ]])
y = np.array([14, 16, -1,  8, -5])
from sklearn.preprocessing import Imputer
imp = Imputer(strategy='mean')
X2 = imp.fit_transform(X)
X2

array([[4.5, 0. , 3. ],
       [3. , 7. , 9. ],
       [3. , 5. , 2. ],
       [4. , 5. , 6. ],
       [8. , 8. , 1. ]])